#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [3]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [23]:
def SymmetricTest(A): 
    i = 0
    finished = False
    while i < np.shape(A)[0] and finished == False: 
        #For each row, now need to look at 
        j=0
        while j < np.size(A[0]): #Iterates for each column on that specific row
            if A[i][j] != A[j][i]:
                return "Matrix is not symmetric"
                finished = True
                break
            else:
                j += 1
                continue
        j = 0
        i += 1
    if i == np.shape(A)[0]:
        return "Matrix is symmetric"

Test your function on the two matrices below

In [24]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [25]:
SymmetricTest(A)

'Matrix is not symmetric'

In [26]:
SymmetricTest(SymMatrix)

'Matrix is symmetric'

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library (`np.zeroes`, `np.ones`, `np.shape`, etc are all ok to use).

In [18]:
def TransposeMatrix(X,n): #A is the matrix and n is the number of rows and column
    result=np.zeros((n,n))
    m = np.shape(X)[0]
    #Since matrix has to be square
    n = m 
    for i in range(m):
        for j in range(n):
            result[j][i]=X[i][j] 
    for r in result:
        print(r)

Check your code by transposing a matrix by checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [19]:
A = np.random.rand(6,6);
print(A)

[[0.39434774 0.57258749 0.46411964 0.45555134 0.07271638 0.41144203]
 [0.69748722 0.23585285 0.21566525 0.37707778 0.14879648 0.211819  ]
 [0.10148628 0.53656031 0.37700244 0.88224694 0.37230228 0.40501185]
 [0.29008574 0.63444343 0.0744693  0.3330515  0.32823757 0.05540558]
 [0.44212567 0.08480147 0.11377723 0.59554089 0.825143   0.72893071]
 [0.54862836 0.35693385 0.06315937 0.97813153 0.93924684 0.06031974]]


In [20]:
AT = TransposeMatrix(A,6)

[0.39434774 0.69748722 0.10148628 0.29008574 0.44212567 0.54862836]
[0.57258749 0.23585285 0.53656031 0.63444343 0.08480147 0.35693385]
[0.46411964 0.21566525 0.37700244 0.0744693  0.11377723 0.06315937]
[0.45555134 0.37707778 0.88224694 0.3330515  0.59554089 0.97813153]
[0.07271638 0.14879648 0.37230228 0.32823757 0.825143   0.93924684]
[0.41144203 0.211819   0.40501185 0.05540558 0.72893071 0.06031974]


In [21]:
ATT=TransposeMatrix(AT,6)
ATT-A

IndexError: tuple index out of range

# Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [9]:
def MaxEntry(A):
    m = np.shape(A)[0] # Rows of the matrix
    # Since matrix is not necessarily square
    n = np.shape(A)[1] # Columns of the matrix
    entries = []
    i = 0
    # First loop iterates through the rows
    while i < m:
        # Iterate through the columns within the first row
        j = 0
        while j < n:
            # Append each entry into a list
            entries.append(A[i][j])
            j += 1
        j = 0
        i += 1
    # Look through the list to find the maximum value
    # Assume largest entry is the first entry
    maxentry = entries[0]
    for x in entries:
        # Check if the current entry in the list is bigger than the previous entry
        if x > maxentry:
            maxentry = x
    return maxentry

Check your result by comparing to `np.max(A)` for the below random matrix

In [11]:
A = np.random.rand(4,5)
print(np.max(A))
MaxEntry(A)

0.8768645880713466


0.8768645880713466

Commit your notebook to git and push it to GitHub.

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()` (`np.shape`, `np.inf`, etc are ok to use).

In [1]:
def L1norm(A):
    columnsums = [] # Empty list to append sums of the columns
    m = np.shape(A)[0] #Rows of the matrix
    n = np.shape(A)[1] #Columns of the matrix
    j = 0
    while j < n: #Looking at the columns of the matrix
        i = 0
        norm = 0
        while i < m: #Iterating through each row of the first column
            norm += np.abs(A[i][j]) 
            i += 1
            columnsums.append(norm)
        i = 0 # Before we add the next column, must have it so that we iterate starting from the first row of the next column
        j += 1
    return np.max(columnsums)

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [4]:
A = np.random.rand(3,4)
print(la.norm(A,1))
L1norm(A)

2.130440879074312


2.130440879074312

## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [6]:
def Linfnorm(A):
    columnsums = [] # Empty list to append sums of the columns
    m = np.shape(A)[0] #Rows of the matrix
    n = np.shape(A)[1] #Columns of the matrix
    i = 0
    while i < m: #Looking at the rows of the matrix
        j = 0
        norm = 0
        while j < n: #Iterating through each row of the first column
            norm += np.abs(A[i][j]) 
            j += 1
            columnsums.append(norm)
        j = 0 # Before we add the next column, must have it so that we iterate starting from the first row of the next column
        i += 1
    return np.max(columnsums)

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [8]:
A = np.random.rand(3,4)
print(la.norm(A,np.inf))
Linfnorm(A)


2.8500671094362366


2.8500671094362366

Commit your notebook to git and push it to GitHub.

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [13]:
A1 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A2 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [14]:
# Using the expression Ax = b. If system is ill-conditioned, a very small change in b gives a large change in x. 
# Use a common 'b' vector for each of the matrices. Matrices are 4 x 4 matrices; 'x' and 'b' are 4 x 1 column vectors 
b = np.array([[1], [2], [3], [4]])

# Solve for 'x' by using x = A^(-1)*b
x1 = la.inv(A1)@b
print("Solution to A1")
print(x1)

print()

x2 = la.inv(A2)@b
print("Solution to A2")
print(x2)

print()

x3 = la.inv(A3)@b
print("Solution to A3")
print(x3)

print()

# Alter column vector 'b'
b_altered = np.array([[1.1],[2],[3],[4]])

# Solve for 'x' again
new_x1 = la.inv(A1)@b_altered
print("New solution to A1")
print(new_x1)

print()

new_x2 = la.inv(A2)@b_altered
print("New solution to A2")
print(new_x2)

new_x3 = la.inv(A3)@b_altered
print("New solution to A3")
print(new_x3)

Solution to A1
[[-74507366.21915984]
 [-37253685.82140911]
 [ 37253687.7088334 ]
 [ 37253684.21585298]]

Solution to A2
[[-0.98741275]
 [ 4.08539139]
 [ 0.09204109]
 [ 1.40102595]]

Solution to A3
[[ 2.15102205]
 [-7.68066892]
 [11.58302528]
 [-6.14655759]]

New solution to A1
[[-4.56447494e+08]
 [-2.28223749e+08]
 [ 2.28223751e+08]
 [ 2.28223748e+08]]

New solution to A2
[[-0.77763587]
 [ 3.93621745]
 [ 0.44140989]
 [ 1.23519189]]
New solution to A3
[[ 2.08844524]
 [-7.47388315]
 [11.41371722]
 [-5.95688858]]


$Answer:$ From comparing the solutions above, A1 is clearly ill-conditioned since a slight change in 'b' gave a large change in 'x'. The significant change in the (3,1) entry in A2 tells us that A2 is also ill-conditioned

In [59]:
# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A1$ and $A2$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{1,2\}$.

SyntaxError: invalid syntax (<ipython-input-59-cb8344339afb>, line 3)

In [60]:
b = np.array([[1],[2],[3],[4]])
delta_b = np.array([[0.1],[0],[0],[0]])

delta_b_L2_norm = la.norm(delta_b,2)
print(delta_b_L2_norm)

print()

b_L2_norm = la.norm(b,2)
print(b_L2_norm)

print()

# To find percentage change in b
print("Percentage change in 'b' = %s " %(100*(delta_b_L2_norm/b_L2_norm)))
 
print()

# Solution of 'x' for A1 from part 3(a) 
print(x1)
x1_L2_norm = la.norm(x1,2)
print(la.norm(x1,2))

print()

# Finding delta x for A1
delta_x1 = new_x1 - x1
print(delta_x1)
delta_x1_L2_norm = la.norm(delta_x1,2)
print(delta_x1_L2_norm)

print()

# Percentage change in 'x' for A1 
print("Percentange change in 'x' for matrix A1= %s" % (100*(delta_x1_L2_norm/x1_L2_norm)))

print()

# Do a similar process to find percentange change in 'x' for A2
print(x2)
x2_L2_norm = la.norm(x2,2)
print(x2_L2_norm)

print()

delta_x2 = new_x2 - x2
print(delta_x2)
delta_x2_L2_norm = la.norm(delta_x2,2)
print(delta_x2_L2_norm)

print()

print("Percentage change in 'x' for A2 = %s" % (100*(delta_x2_L2_norm/x2_L2_norm)))

0.1

5.477225575051661

Percentage change in 'b' = 1.8257418583505536 

[[-74507366.21915984]
 [-37253685.82140911]
 [ 37253687.7088334 ]
 [ 37253684.21585298]]
98563984.11061738

[[-3.81940128e+08]
 [-1.90970064e+08]
 [ 1.90970064e+08]
 [ 1.90970064e+08]]
505259296.4788094

Percentange change in 'x' for matrix A1= 512.6206098890665

[[-0.98741275]
 [ 4.08539139]
 [ 0.09204109]
 [ 1.40102595]]
4.431337491585107

[[ 0.20977688]
 [-0.14917393]
 [ 0.3493688 ]
 [-0.16583406]]
0.4645629093910389

Percentage change in 'x' for A2 = 10.483582220339144


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

$Answer:$ The matrix A1 is more sensitive to small changes in b as we can see from the percentages above. This answer could have been guessed in part (a) of this question by looking at how much the solution to A1 changed just by slightly adjusting an entry of 'b' by 0.1. 

Commit your notebook to git and push it to GitHub.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [20]:
A = np.array([[2.65287619, 1.58615494, 1.47170961, 1.40586081],
       [1.58615494, 1.17577323, 0.72084593, 0.79382861],
       [1.47170961, 0.72084593, 1.18111969, 0.6654689 ],
       [1.40586081, 0.79382861, 0.6654689 , 0.84502394]])

Check your answers against Numpy's results from `la.eig(A)`

Commit your notebook to git and push it to GitHub. Upload your completed assignment to BrightSpace.